future: true

# core settings
title: Michael Cassio
email: catastrio@gmail.com
email_address: catastrio@gmail.com

# bio's
description: > # this means to ignore newlines until "baseurl:"
  Michael Cassio is a programmer, writer and streamer based in Yuma, Arizona.
  with a deep, passionate interest in story telling and expressing ideas creatively, I pour my best into every project.
short_description: "David Young is a Web Developer based in Brisbane, Australia with a keen interest in Website Development and Design."
base_keywords: "web, developer, blog, web developer, brisbane, australia, david, young, david young"

# URLs
baseurl: "" # subpath, eg /blog
url: "https://davidyoung.tech" # base url
theme_colour: "#F4F2F0"

# usernames
twitter_username: dayvidwhy
github_username:  dayvidwhy

# Build settings
markdown: kramdown
sass:
  style: compressed

exclude:
    - Gemfile
    - Gemfile.lock
    - Rakefile
    - .mdspell
    - CNAME
    - README.md