future: true

# core settings
title: Michael Cassio
email: catastrio@gmail.com
email_address: catastrio@gmail.com

# bio's
description: > # this means to ignore newlines until "baseurl:"
  Michael Cassio is a writer, programmer and streamer based in Arizona
  with a deep, passionate interest in helping people express ideas creatively.
short_description: "Michael Cassio is a writer, programemr and streamer based in Arizona."
base_keywords: "web, developer, blog, web developer, brisbane, australia, david, young, david young"

# URLs
baseurl: "" # subpath, eg /blog
url: "https://catastrio.github.io" # base url
theme_colour: "#F4F2F0"

# usernames
twitter_username: Catastrio
github_username:  Catastrio

# Build settings
markdown: kramdown
sass:
  style: compressed

exclude:
    - Gemfile
    - Gemfile.lock
    - Rakefile
    - .mdspell
    - CNAME
    - README.md